[project]
name = "mcp-sqlite"
version = "0.1.0"
description = "Making local data equally accessible to AI agents and humans. Datasette-compatible!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.9.2",
]

[dependency-groups]
dev = [
    "mcp[cli]>=1.9.2",
]
